/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPrincipal.java
 *
 * Created on 21-may-2010, 14:42:26
 */
package PaqFormulario;

import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.text.DateFormat;
import java.util.Date;

/**
 * PP
 *
 * @author Danny Veron
 */
public final class FrmPrincipal extends javax.swing.JFrame {

    private Connection cn = null;
    private ResultSet rs = null;
    static logoPrincipal logo;
    Thread OrdenCompra;

    /**
     * Creates new form FrmPrincipal
     */
    @SuppressWarnings("static-access")
    public FrmPrincipal() {
        initComponents();
        centrar();//cargar();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.pack();
        Date date = new Date();
        DateFormat df = DateFormat.getDateInstance(DateFormat.FULL);
        lbl.setText(df.format(date));
        if(Integer.parseInt(AcesoUsuario.CodigoUsuario)>1){
            MenUsuario.setEnabled(false);
        }
    }

    public void cargar() {
        logo = new logoPrincipal();
        logo.setSize(960, 600);
        this.add(logo);
        logo.setLocation(40, 30);
        this.pack();
    }

    public void centrar() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frame = this.getSize();
        setLocation((pantalla.width / 2 - (frame.width / 2)), 0);

    }

    public void AjustarAPantalla() {
    }

    public static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    public static void CambiarPanel() {
        logo.removeAll();
        logo.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        menPrincipal = new javax.swing.JMenuBar();
        menArc = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menCiu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenUsuario = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menPro = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menInf = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        menAyu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HCOC Soft");
        setResizable(false);

        lbl.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(0, 153, 0));

        menPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 2, true));

        menArc.setMnemonic('a');
        menArc.setText("Archivo"); // NOI18N
        menArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArcActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Articulo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menArc.add(jMenuItem3);

        jMenuItem1.setText("Departamento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menArc.add(jMenuItem1);

        menCiu.setText("Proveedor");
        menCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCiuActionPerformed(evt);
            }
        });
        menArc.add(menCiu);

        jMenuItem2.setText("Tipo De Articulo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menArc.add(jMenuItem2);

        MenUsuario.setText("Usuario"); // NOI18N
        MenUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenUsuarioActionPerformed(evt);
            }
        });
        menArc.add(MenUsuario);

        jMenuItem4.setText("Salir"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menArc.add(jMenuItem4);

        menPrincipal.add(menArc);

        menPro.setMnemonic('G');
        menPro.setText("Gestion"); // NOI18N
        menPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProActionPerformed(evt);
            }
        });

        jMenu2.setText("OC");

        jMenuItem5.setText("Agregar/Modificar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Imprimir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        menPro.add(jMenu2);

        menPrincipal.add(menPro);

        menInf.setMnemonic('i');
        menInf.setText("Informe"); // NOI18N

        jMenuItem7.setText("O.C.");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menInf.add(jMenuItem7);

        menPrincipal.add(menInf);

        menAyu.setText("Ayuda");
        menPrincipal.add(menAyu);

        setJMenuBar(menPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenUsuarioActionPerformed
        Usuario usu = new Usuario(this, true);
        usu.setVisible(true);
    }//GEN-LAST:event_MenUsuarioActionPerformed

    private void menProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProActionPerformed
    }//GEN-LAST:event_menProActionPerformed

    private void menCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCiuActionPerformed
        Proveedor pro = new Proveedor(this, true);
        pro.setVisible(true);
    }//GEN-LAST:event_menCiuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Catedra cat = new Catedra(this, true);
        cat.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menArcActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TipoArticulo ta = new TipoArticulo(this, true);
        ta.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Articulo ar = new Articulo(this, true);
        ar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        OC oc = new OC(this, false);
        oc.setVisible(true);
        OC.btnnue.grabFocus();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       ReporteOC ro=new ReporteOC(this, true);
       ro.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrmImprimir im= new FrmImprimir(this,false );
        im.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new FrmPrincipal().setVisible(true);

                } catch (Exception ex) {
                }

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenUsuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    public static javax.swing.JLabel lbl;
    private javax.swing.JMenu menArc;
    private javax.swing.JMenu menAyu;
    private javax.swing.JMenuItem menCiu;
    private javax.swing.JMenu menInf;
    private javax.swing.JMenuBar menPrincipal;
    private javax.swing.JMenu menPro;
    // End of variables declaration//GEN-END:variables
}
